package com.cts.rivio.pages;

import com.cts.rivio.constants.AppConstants;
import com.cts.rivio.utils.WaitUtils;
import org.openqa.selenium.*;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

/**
 * LoginPage – mirrors features/auth-users/login/login.component.html.
 *
 * Real DOM facts that drove these selectors:
 *   - Email input has id="email" and formcontrolname="email"
 *   - Password uses PrimeNG <p-password id="password">; the real input is
 *     inside that component as `p-password input` (type stays "password" unless
 *     the eye toggle is clicked).
 *   - Submit button is the only button[type='submit'] on the page; its label
 *     reads "ACCESS DASHBOARD →".
 *   - Inline error renders inside a div with bg-red-50 + role="alert" semantics.
 *   - Brand panel contains the literal text "RIVIO" and the tagline.
 */
public class LoginPage {

    private WebDriver driver;

    // ── Locators ──────────────────────────────────────────────────────────────

    @FindBy(id = "email")
    private WebElement emailInput;

    // The actual <input> generated by <p-password id="password">
    @FindBy(css = "p-password#password input, #password input, input[type='password']")
    private WebElement passwordInput;

    @FindBy(css = "button[type='submit']")
    private WebElement loginButton;

    // Show/hide eye icon inside p-password
    @FindBy(css = "p-password .p-password-toggle-mask-icon, p-password .p-icon-wrapper")
    private WebElement passwordToggleEye;

    // The inline error banner shown above the form on failure
    @FindBy(css = "div.bg-red-50, div[class*='bg-red-50'], p.text-red-700")
    private WebElement errorBanner;

    @FindBy(css = "h2")
    private WebElement welcomeBackHeading;

    // Brand panel checks
    @FindBy(xpath = "//*[normalize-space(text())='RIVIO']")
    private WebElement brandLogoText;

    @FindBy(xpath = "//*[contains(normalize-space(.),'Workforce')]")
    private WebElement workforceTagline;

    // ── Constructor ───────────────────────────────────────────────────────────

    public LoginPage(WebDriver driver) {
        this.driver = driver;
        PageFactory.initElements(driver, this);
    }

    // ── Actions ───────────────────────────────────────────────────────────────

    public void enterEmail(String email) {
        WaitUtils.waitForVisibility(driver, emailInput);
        emailInput.clear();
        // jsSetValue first to handle Angular control, then sendKeys to fire native input event
        WaitUtils.jsSetValue(driver, emailInput, email);
        emailInput.sendKeys(Keys.SPACE, Keys.BACK_SPACE);
    }

    public void enterPassword(String password) {
        WaitUtils.waitForVisibility(driver, passwordInput);
        passwordInput.clear();
        WaitUtils.jsSetValue(driver, passwordInput, password);
        passwordInput.sendKeys(Keys.SPACE, Keys.BACK_SPACE);
    }

    public void clickLoginButton() {
        WaitUtils.dismissPopupsIfPresent(driver);
        WaitUtils.safeClick(driver, loginButton);
    }

    public void clickPasswordToggle() {
        try { WaitUtils.safeClick(driver, passwordToggleEye); } catch (Exception ignored) {}
    }

    /**
     * Full login: fills credentials, submits, waits for URL to leave the login route.
     * Returns a DashboardPage handle (callers can pivot to other pages as needed).
     */
    public DashboardPage login(String email, String password) {
        enterEmail(email);
        enterPassword(password);
        clickLoginButton();
        waitForLoginToComplete();
        return new DashboardPage(driver);
    }

    /** Stays on the login page so error-message assertions work. */
    public LoginPage loginExpectingFailure(String email, String password) {
        enterEmail(email);
        enterPassword(password);
        clickLoginButton();
        // Wait up to 8 seconds for either the inline error banner OR the URL to leave /login.
        try {
            new org.openqa.selenium.support.ui.WebDriverWait(driver, java.time.Duration.ofSeconds(8))
                .until(d -> !d.findElements(
                    org.openqa.selenium.By.cssSelector(
                        "div.bg-red-50, div[class*='bg-red-50'], p.text-red-700")).isEmpty()
                || !d.getCurrentUrl().contains("/login"));
        } catch (Exception ignored) {}
        return this;
    }

    public DashboardPage loginUsingEnterKey(String email, String password) {
        enterEmail(email);
        enterPassword(password);
        passwordInput.sendKeys(Keys.ENTER);
        waitForLoginToComplete();
        return new DashboardPage(driver);
    }

    private void waitForLoginToComplete() {
        try { WaitUtils.waitForUrlNotContains(driver, "/login"); } catch (Exception ignored) {}
        WaitUtils.waitForAngularLoad(driver);
        WaitUtils.dismissPopupsIfPresent(driver);
    }

    // ── Verifications ─────────────────────────────────────────────────────────

    public boolean isLoginPageDisplayed() {
        try {
            WaitUtils.waitForVisibility(driver, emailInput);
            return emailInput.isDisplayed() && passwordInput.isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }

    public boolean isErrorDisplayed() {
        try { return errorBanner.isDisplayed(); }
        catch (NoSuchElementException | StaleElementReferenceException e) { return false; }
    }

    public String getErrorMessage() {
        try {
            WaitUtils.waitForVisibility(driver, errorBanner);
            return errorBanner.getText().trim();
        } catch (Exception e) {
            return "";
        }
    }

    public boolean isBrandPanelDisplayed() {
        try { return brandLogoText.isDisplayed() && workforceTagline.isDisplayed(); }
        catch (Exception e) { return false; }
    }

    public String getSubmitButtonText() {
        try { return loginButton.getText().trim(); }
        catch (Exception e) { return ""; }
    }

    public boolean isSubmitButtonEnabled() {
        try { return loginButton.isEnabled(); }
        catch (Exception e) { return false; }
    }

    public boolean isPasswordMasked() {
        try {
            String type = passwordInput.getAttribute("type");
            return "password".equalsIgnoreCase(type);
        } catch (Exception e) { return true; }
    }

    public String getCurrentUrl() { return driver.getCurrentUrl(); }
    public String getPageTitle()  { return driver.getTitle(); }
}
